- name: 'A test for #69677. See https://github.com/ansible/ansible/issues/69677'
  hosts: somegroup
  
#---
# PRE-TASKS
#---
  pre_tasks:
  - name: Shows involved versions
    debug:
      msg:
      - "Python version: '{{ ansible_python_version }}'."
      - "Ansible version '{{ ansible_version.string }}'."
      
#---
# TASKS
#---
  tasks:
  # this works, but doesn't cover the requested use-case
  - block:
    - name: Original variables
      debug:
        msg:
        - "{{ example_case }}:"
        - "original list: {{ mergeable_list }}"
        - "original dict: {{ mergeable_dict }}"
        
    - name: Merges inventory variables with different names.
      debug:
        msg:
        - "{{ example_case }}:"
        - "merged lists: {{ different_merged_list }}"
        - "merged dicts: {{ different_merged_dict }}"
    when: example_case == 'DOES WORK'
    
  # this does NOT work
  - name: Tries to overload inventory variables.
    debug:
      msg:
      - "{{ example_case }}:"
      - "overloaded list: {{ mergeable_list }}"
      - "overloaded dict: {{ mergeable_dict }}"
    when: example_case == 'DOES NOT WORK'
