# See https://github.com/ansible/ansible/issues/69677
- name: "A test for #69677"
  hosts: somegroup
  connection: local
  
#---
# TASKS
#---
  tasks:
  - name: "A test for #69677"
    debug:
      msg:
      # these don't work when trying to "overload" these variables' contents
      - "merged_list: {{ merged_list }}"
      - "merged_dict: {{ merged_dict }}"
      # these do work, but don't cover the requested use-case
      - "different_merged_list: {{ different_merged_list }}"
      - "different_merged_dict: {{ different_merged_dict }}"

